# Generated by Django 5.2.5 on 2025-08-31 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('pessoa_falecida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(verbose_name='Data do Agendamento')),
                ('hora_agendamento', models.TimeField(verbose_name='Hora do Agendamento')),
                ('local_velorio', models.CharField(max_length=200, verbose_name='Local do Velório')),
                ('local_sepultamento', models.CharField(max_length=200, verbose_name='Local do Sepultamento')),
                ('data_sepultamento', models.DateTimeField(verbose_name='Data do Sepultamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario', verbose_name='Funcionário Responsável')),
                ('pessoa_falecida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pessoa_falecida.pessoafalecida', verbose_name='Pessoa Falecida')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_agendamento'],
            },
        ),
    ]
