# Generated by Django 5.2.5 on 2025-08-31 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFalecida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('data_falecimento', models.DateField(verbose_name='Data de Falecimento')),
                ('causa_obito', models.TextField(verbose_name='Causa do Óbito')),
                ('local_obito', models.CharField(max_length=200, verbose_name='Local do Óbito')),
                ('documento_cpf_rg', models.CharField(max_length=20, verbose_name='CPF/RG')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_falecidas', to='familia.familia', verbose_name='Família')),
            ],
            options={
                'verbose_name': 'Pessoa Falecida',
                'verbose_name_plural': 'Pessoas Falecidas',
                'ordering': ['-data_falecimento'],
            },
        ),
    ]
