# Generated by Django 5.2.5 on 2025-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa_falecida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafalecida',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pessoas_falecidas/', verbose_name='Foto do Falecido'),
        ),
    ]
