# Generated by Django 5.2.5 on 2025-08-31 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_servico', '0001_initial'),
        ('pessoa_falecida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_adicional', models.TextField(blank=True, null=True, verbose_name='Descrição Adicional')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final')),
                ('item_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_servico.itemservico', verbose_name='Item de Serviço')),
                ('pessoa_falecida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_contratados', to='pessoa_falecida.pessoafalecida', verbose_name='Pessoa Falecida')),
            ],
            options={
                'verbose_name': 'Serviço Contratado',
                'verbose_name_plural': 'Serviços Contratados',
                'ordering': ['pessoa_falecida', 'item_servico'],
            },
        ),
    ]
