# Generated by Django 5.2.5 on 2025-09-02 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_contratado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicocontratado',
            options={'ordering': ['-data_contratacao', 'pessoa_falecida', 'item_servico'], 'verbose_name': 'Serviço Contratado', 'verbose_name_plural': 'Serviços Contratados'},
        ),
        migrations.AddField(
            model_name='servicocontratado',
            name='data_contratacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Contratação'),
        ),
        migrations.AddField(
            model_name='servicocontratado',
            name='numero_nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota Fiscal'),
        ),
    ]
