# Generated by Django 5.2.5 on 2025-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_contratado', '0002_alter_servicocontratado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicocontratado',
            options={'ordering': [], 'verbose_name': 'Serviço Contratado', 'verbose_name_plural': 'Serviços Contratados'},
        ),
        migrations.AddField(
            model_name='servicocontratado',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos_contratados_imagens/', verbose_name='Imagem do Serviço'),
        ),
    ]
