# Generated by Django 5.2.5 on 2025-09-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico_contratado', '0003_alter_servicocontratado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicocontratado',
            options={'ordering': ['-data_contratacao', 'pessoa_falecida', 'item_servico'], 'verbose_name': 'Serviço Contratado', 'verbose_name_plural': 'Serviços Contratados'},
        ),
        migrations.RemoveField(
            model_name='servicocontratado',
            name='imagem',
        ),
    ]
