# Generated by Django 5.2.6 on 2025-09-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_servico', '0003_alter_itemservico_imagem'),
        ('servico_contratado', '0004_alter_servicocontratado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicocontratado',
            options={'ordering': ['-data_contratacao', 'pessoa_falecida'], 'verbose_name': 'Serviço Contratado', 'verbose_name_plural': 'Serviços Contratados'},
        ),
        migrations.RemoveField(
            model_name='servicocontratado',
            name='item_servico',
        ),
        migrations.RemoveField(
            model_name='servicocontratado',
            name='valor_final',
        ),
        migrations.AddField(
            model_name='servicocontratado',
            name='taxa_imposto',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Taxa de imposto em porcentagem (padrão: 10%)', max_digits=5, verbose_name='Taxa de Imposto (%)'),
        ),
        migrations.CreateModel(
            name='ItemServicoContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('item_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_servico.itemservico', verbose_name='Item de Serviço')),
                ('servico_contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='servico_contratado.servicocontratado', verbose_name='Serviço Contratado')),
            ],
            options={
                'verbose_name': 'Item do Serviço Contratado',
                'verbose_name_plural': 'Itens dos Serviços Contratados',
                'unique_together': {('servico_contratado', 'item_servico')},
            },
        ),
    ]
