# Generated by Django 5.2.6 on 2025-09-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico_contratado', '0005_alter_servicocontratado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicocontratado',
            name='pdf_nota_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='PDF da Nota Fiscal'),
        ),
    ]
