# Generated by Django 5.2.5 on 2025-08-31 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa_falecida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=200, verbose_name='Nome do Plano')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('pessoa_falecida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planejamento', to='pessoa_falecida.pessoafalecida', verbose_name='Pessoa Falecida')),
            ],
            options={
                'verbose_name': 'Planejamento',
                'verbose_name_plural': 'Planejamentos',
                'ordering': ['nome_plano'],
            },
        ),
    ]
