# Generated by Django 5.2.5 on 2025-08-31 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFuneraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funeraria', models.CharField(default='Sistema Funerária', help_text='Nome que aparecerá no sistema', max_length=200, verbose_name='Nome da Funerária')),
                ('slogan', models.CharField(blank=True, help_text='Frase que representa a funerária', max_length=300, null=True, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, help_text='Logo da funerária (recomendado: 200x80px)', null=True, upload_to='configuracoes/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Ícone do site (recomendado: 32x32px)', null=True, upload_to='configuracoes/favicons/', verbose_name='Favicon')),
                ('telefone_principal', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato: (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone Principal')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato: (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone Secundário')),
                ('email_principal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Principal')),
                ('email_comercial', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Comercial')),
                ('endereco_completo', models.TextField(blank=True, help_text='Endereço completo da funerária', null=True, verbose_name='Endereço Completo')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Formato: 12345-678', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='Formato: 12.345.678/0001-90', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('whatsapp_numero', models.CharField(blank=True, help_text='Número com código do país (5511999999999)', max_length=20, null=True, verbose_name='WhatsApp')),
                ('cor_primaria', models.CharField(default='#0d6efd', help_text='Cor principal do sistema (formato: #000000)', max_length=7, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#6c757d', help_text='Cor secundária do sistema (formato: #000000)', max_length=7, verbose_name='Cor Secundária')),
                ('horario_funcionamento', models.TextField(blank=True, help_text='Horários de atendimento da funerária', null=True, verbose_name='Horário de Funcionamento')),
                ('ativa', models.BooleanField(default=True, help_text='Apenas uma configuração pode estar ativa por vez', verbose_name='Configuração Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Configuração da Funerária',
                'verbose_name_plural': 'Configurações da Funerária',
                'ordering': ['-ativa', '-data_atualizacao'],
            },
        ),
    ]
