# Generated by Django 5.2.5 on 2025-08-31 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familia', '0001_initial'),
        ('pessoa_falecida', '0001_initial'),
        ('servico_contratado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato de Serviços'), ('certidao', 'Certidão de Óbito'), ('memorial', 'Memorial'), ('orcamento', 'Orçamento'), ('recibo', 'Recibo'), ('declaracao', 'Declaração'), ('compartilhamento', 'Página de Compartilhamento')], max_length=20, verbose_name='Tipo de Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('conteudo_html', models.TextField(help_text='Template HTML com variáveis Django', verbose_name='Conteúdo HTML')),
                ('css_personalizado', models.TextField(blank=True, help_text='Estilos CSS específicos para este template', null=True, verbose_name='CSS Personalizado')),
                ('variaveis_disponiveis', models.TextField(blank=True, help_text='Lista de variáveis que podem ser usadas no template', null=True, verbose_name='Variáveis Disponíveis')),
                ('ativo', models.BooleanField(default=True, verbose_name='Template Ativo')),
                ('padrao', models.BooleanField(default=False, help_text='Template padrão para este tipo de documento', verbose_name='Template Padrão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Template de Documento',
                'verbose_name_plural': 'Templates de Documentos',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID do Documento')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título do Documento')),
                ('conteudo_html', models.TextField(verbose_name='Conteúdo HTML Gerado')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos/pdfs/', verbose_name='Arquivo PDF')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('gerado', 'Gerado'), ('enviado', 'Enviado'), ('assinado', 'Assinado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('publico', models.BooleanField(default=False, help_text='Permite acesso via URL pública', verbose_name='Documento Público')),
                ('senha_acesso', models.CharField(blank=True, help_text='Senha para acesso ao documento público', max_length=50, null=True, verbose_name='Senha de Acesso')),
                ('data_expiracao', models.DateTimeField(blank=True, help_text='Data limite para acesso público', null=True, verbose_name='Data de Expiração')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Número de Visualizações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='familia.familia', verbose_name='Família')),
                ('pessoa_falecida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa_falecida.pessoafalecida', verbose_name='Pessoa Falecida')),
                ('servico_contratado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico_contratado.servicocontratado', verbose_name='Serviço Contratado')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criador')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.templatedocumento', verbose_name='Template Utilizado')),
            ],
            options={
                'verbose_name': 'Documento Gerado',
                'verbose_name_plural': 'Documentos Gerados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('email', 'Email'), ('link_direto', 'Link Direto'), ('qr_code', 'QR Code')], max_length=20, verbose_name='Plataforma')),
                ('destinatario', models.CharField(blank=True, help_text='Email, telefone ou nome do destinatário', max_length=200, null=True, verbose_name='Destinatário')),
                ('mensagem_personalizada', models.TextField(blank=True, null=True, verbose_name='Mensagem Personalizada')),
                ('data_compartilhamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Compartilhamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Compartilhou')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.documentogerado', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Documento',
                'verbose_name_plural': 'Compartilhamentos de Documentos',
                'ordering': ['-data_compartilhamento'],
            },
        ),
        migrations.CreateModel(
            name='MetaTagsDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_title', models.CharField(max_length=200, verbose_name='OG Title')),
                ('og_description', models.TextField(max_length=300, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='documentos/og_images/', verbose_name='OG Image')),
                ('og_type', models.CharField(default='article', max_length=50, verbose_name='OG Type')),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=50, verbose_name='Twitter Card')),
                ('twitter_title', models.CharField(max_length=200, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(max_length=200, verbose_name='Twitter Description')),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='documentos/twitter_images/', verbose_name='Twitter Image')),
                ('whatsapp_title', models.CharField(max_length=200, verbose_name='WhatsApp Title')),
                ('whatsapp_description', models.TextField(max_length=300, verbose_name='WhatsApp Description')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documentos.documentogerado', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Meta Tags do Documento',
                'verbose_name_plural': 'Meta Tags dos Documentos',
            },
        ),
    ]
