# Generated by Django 5.2.5 on 2025-08-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('grau_parentesco', models.CharField(max_length=100, verbose_name='Grau de Parentesco')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('endereco', models.TextField(verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
                'ordering': ['nome_responsavel'],
            },
        ),
    ]
