# Generated by Django 5.2.5 on 2025-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemservico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='itens_servico_imagens/', verbose_name='Imagem do Item'),
        ),
    ]
