# Generated by Django 5.2.5 on 2025-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_servico', '0002_itemservico_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemservico',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do item/serviço', null=True, upload_to='itens_servicos/', verbose_name='Imagem'),
        ),
    ]
