# Generated by Django 5.2.5 on 2025-08-31 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa_falecida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status')),
                ('pessoa_falecida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiros', to='pessoa_falecida.pessoafalecida', verbose_name='Pessoa Falecida')),
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Financeiros',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
