# Generated by Django 5.2.6 on 2025-09-03 22:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('servico_contratado', '0006_servicocontratado_pdf_nota_fiscal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['-data_vencimento', '-data_criacao'], 'verbose_name': 'Financeiro', 'verbose_name_plural': 'Financeiros'},
        ),
        migrations.AddField(
            model_name='financeiro',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('boleto', 'Boleto Bancário')], max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='servico_contratado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_financeiros', to='servico_contratado.servicocontratado', verbose_name='Serviço Contratado'),
        ),
    ]
