# Generated by Django 5.2.5 on 2025-09-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('adm', 'Administrador'), ('vendedor', 'Vendedor'), ('florista', 'Florista'), ('coveiro', 'Coveiro'), ('preparador', 'Preparador')], help_text='Cargo do funcionário na funerária', max_length=20, verbose_name='Cargo'),
        ),
    ]
